### ISSUE TITLE
Deprecated Player-Achievement-Awarded-Event 

### ISSUE THREAD

**Issue by bierdosenhalter** [zeroBzeroT/QueueServerPlugin#25]
`[08:55:28 WARN]: "QueuePlugin v1.0-SNAPSHOT" has registered a listener for org.bukkit.event.player.PlayerAchievementAwardedEvent on method "public void org.cloudanarchy.queueplugin.QueuePlugin.onAchievement(org.bukkit.event.player.PlayerAchievementAwardedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].`

**Comment by nothub** [comment]
Fixed at some point in the past. Currently the plugins listens for `PlayerAdvancementDoneEvent`.
